### ISSUE TITLE
Project status on README

### ISSUE THREAD

**Issue by malespiaut** [ThemeParkWorld/OpenTPW#20]
Hello,

I think that a short section of the README should be dedicated about the progress of the project.

For instance, I would like to know which file format have been fully documented or not, to get an idea about which part of the project need immediate help.
This could be displayed as a list in the README.

I've read the wiki about the BF4 (Bullfrog Font File Format), and wrote a small extractor following the specification, but it appears that this file is either encrypted or compressed.
Since that isn't documented in the wiki, I concluse that the issue of reading and using BF4 files isn't resolved.

Best regards.

**Comment by xezno** [comment]
Added this
