### ISSUE TITLE
How to get it running?

### ISSUE THREAD

**Issue by hackgrid** [ThemeParkWorld/OpenTPW#9]
Hi,

thanks for working on this, this will be great! :-)

How do you run the current version?
I build it, but it always fails to locate files in the "contents"-folders, which is missing from the GIT repo.

Does this content need to get generated from the original game data?
How can I do this?

Also I noticed, that the "launchSettings.json" file contains a hardcoded path:

_"workingDirectory": `"F:\\Projects\\OpenTPW"_

Thanks and regards

**Comment by xezno** [comment]
I changed the hardcoded working directory so this should be fixed now

**Comment by hackgrid** [comment]
Sorry about that, my fault, I use VS in a VM and copied the bin folder to my main machine, that is why it missed the contents-folder!

Everthing works fine now, thanks! :)
